# -*- coding: utf-8 -*-
"""sign_language_ui.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BL4if__QTnSV05-Egri0y6sp_w1Mq7S2
"""

# sign_language_ui.py
import streamlit as st
import cv2
import numpy as np
from tensorflow.keras.models import load_model
import tempfile
import pyttsx3

# Load model
model = load_model('sign_language_model.h5')

# Label list for A–Z
labels = [chr(i) for i in range(65, 91)]

st.set_page_config(page_title="Sign Language Detector", layout="centered")
st.title("🖐️ Sign Language Detection using Deep Learning")

st.markdown("""
Upload or capture an image showing your **hand sign**,
and the model will predict the corresponding **English alphabet**.
""")

# Camera or file upload
option = st.radio("Choose Input Mode:", ("Use Camera", "Upload Image"))

if option == "Use Camera":
    camera_input = st.camera_input("Capture Hand Sign 👇")

    if camera_input:
        with tempfile.NamedTemporaryFile(delete=False) as temp:
            temp.write(camera_input.getvalue())
            frame = cv2.imread(temp.name)

        img = cv2.resize(frame, (64, 64))
        img = img / 255.0
        img = np.expand_dims(img, axis=0)

        prediction = model.predict(img)
        label = labels[np.argmax(prediction)]

        st.subheader(f"🔤 Predicted Sign: **{label}**")

        # Optional Speech Output
        engine = pyttsx3.init()
        engine.say(f"The detected sign is {label}")
        engine.runAndWait()

else:
    uploaded_file = st.file_uploader("Upload Hand Sign Image", type=["jpg", "png", "jpeg"])
    if uploaded_file is not None:
        file_bytes = np.asarray(bytearray(uploaded_file.read()), dtype=np.uint8)
        frame = cv2.imdecode(file_bytes, 1)

        img = cv2.resize(frame, (64, 64))
        img = img / 255.0
        img = np.expand_dims(img, axis=0)

        prediction = model.predict(img)
        label = labels[np.argmax(prediction)]

        st.image(frame, caption="Uploaded Image")
        st.subheader(f"🔤 Predicted Sign: **{label}**")

        engine = pyttsx3.init()
        engine.say(f"The detected sign is {label}")
        engine.runAndWait()